### ISSUE TITLE
Blending with ARB_blend_func_extended 

### ISSUE THREAD

**Issue by Enichan** [astiopin/webgl_fonts#2]
I've been looking for a while but can't seem to figure it out. How would this work if ARB_blend_func_extended were available, and would that make it so the subpixel rendering would work on a non-flat color background?

**Comment by astiopin** [comment]
If `ARB_blend_func_extended` is supported, you can output subpixel coverage as a secondary color in the fragment shader and use `glBlendFunc( GL_SRC1_COLOR, GL_ONE_MINUS_SRC1_COLOR )` for blending.
