### ISSUE TITLE
Atlas

### ISSUE THREAD

**Issue by WolfieWerewolf** [astiopin/webgl_fonts#3]
Hi.. Just wondering what you used to generate the atlas and metrics file?
Thanks
/W

**Comment by astiopin** [comment]
I wrote small tool based on [stb_truetype](https://github.com/nothings/stb/blob/master/stb_truetype.h). Ugly and hackish, not ready to publish it yet.

**Comment by WolfieWerewolf** [comment]
@astiopin hackish or not your text is beautiful!  Thank you so much for sharing.

**Comment by astiopin** [comment]
Finaly finished the atlas tool. Check it out. [https://github.com/astiopin/sdf_atlas](https://github.com/astiopin/sdf_atlas)

**Comment by WolfieWerewolf** [comment]
Thank you for remembering me!!! I am away for the week but will check it
out as soon as I get back.  Excellent t stuff!!! THANK YOU.
