### ISSUE TITLE
How you detect subpixel configuration?

### ISSUE THREAD

**Issue by VladimirShestakov** [astiopin/webgl_fonts#5]
How you detect subpixel configuration? Or use most popular RGB (not other)?

![image](https://user-images.githubusercontent.com/614740/68592839-1106e180-04a5-11ea-9230-604e284f0083.png)

**Comment by astiopin** [comment]
I'm just using RGB at the moment. One possible way to detect subpixel configuration is to use custom font with a single glyph (say, line or square), draw it with HTML canvas API, and then analyze resulting pixels.
