### ISSUE TITLE
Amazing, but can it scale?

### ISSUE THREAD

**Issue by oomek** [astiopin/webgl_fonts#6]
The quality of atlas rendering with your method greatly exceeds all other methods I've seen so far, even oversampled ones. The gradients are so smooth. I have one question though regarding your text rendering technique. There is a lot of hinting going on. Is it possible to achieve smooth scaling/rotating of text with your shaders?

**Comment by oomek** [comment]
After removing all rounding functions it scales and rotates smoothly. Hinting disabled.
![image](https://user-images.githubusercontent.com/2974860/74741182-3fd6e580-5254-11ea-9755-05bc281b7de1.png)

**Comment by astiopin** [comment]
Hinting should be disabled during scaling/rotation or you would get ugly aliasing artifacts. Hinting option is not a boolean actually, it is a float value in the code, so you can make smooth transition from unhinted to hinted text during animation.

**Comment by oomek** [comment]
Good idea, thanks
