### ISSUE TITLE
Blending possible in Chrome

### ISSUE THREAD

**Issue by oomek** [astiopin/webgl_fonts#7]
Could you tell me what was the reason of using a workaround mentioned here?
https://github.com/astiopin/webgl_fonts/blob/e83f9c6ba9bb3f43d15cd17660e0e928f7734956/src/fshader.js#L104
I did some experiments and I've managed to do a proper blending for cleartype with 3 samples with offset for each channel instead of fake fringing.

```
        gl.enable(gl.BLEND);
        gl.blendFunc(gl.CONSTANT_COLOR, gl.ONE_MINUS_SRC_COLOR);

        gl.blendEquation( gl.FUNC_ADD );
        gl.blendColor( font_color[0], font_color[1], font_color[2], 1.0);
```

**Comment by oomek** [comment]
The shader is simplified:
```
precision mediump float;

uniform sampler2D font_tex;
uniform float hint_amount;
uniform float subpixel_amount;

uniform vec3 bg_color;
uniform vec3 font_color;

varying vec2  tc0;
varying float doffset;
varying float sdf_texel;
varying float subpixel_offset;

float lstep( float a, float b, float x )
{
    return clamp(( x - a ) / ( b - a ), 0.0, 1.0 );
}

void main() {
    // Sampling the texture, L pattern
    float sdf       = texture2D( font_tex, tc0 ).r;
    float sdf_north = texture2D( font_tex, tc0 + vec2( 0.0, sdf_texel ) ).r;
    float sdf_east  = texture2D( font_tex, tc0 + vec2( sdf_texel, 0.0 ) ).r;

    // Estimating stroke direction by the distance field gradient vector
    vec2  sgrad     = vec2( sdf_east - sdf, sdf_north - sdf );
    float sgrad_len = max( length( sgrad ), 1.0 / 128.0 );
    vec2  grad      = sgrad / vec2( sgrad_len );
    float vgrad = abs( grad.y ); // 0.0 - vertical stroke, 1.0 - horizontal one

    float horz_scale  = 1.0 - subpixel_amount * 0.333; // Blurring vertical strokes along the X axis a bit
    float vert_scale  = 0.5; // While adding some contrast to the horizontal strokes
    float hdoffset    = mix( doffset * horz_scale, doffset * vert_scale, vgrad );
    float res_doffset = mix( doffset, hdoffset, hint_amount );

    vec2 offs = vec2( subpixel_amount * res_doffset * sdf_texel * 16.0, 0.0 ); // not sure about 16.0, sdf_size?

    float sdf_r = texture2D( font_tex, tc0 - offs ).r;
    float sdf_b = texture2D( font_tex, tc0 + offs ).r;

    float alpha_r = lstep( 0.5 - res_doffset, 0.5 + res_doffset, sdf_r );
    float alpha_g = lstep( 0.5 - res_doffset, 0.5 + res_doffset, sdf );
    float alpha_b = lstep( 0.5 - res_doffset, 0.5 + res_doffset, sdf_b );

    vec3 color = vec3( alpha_r, alpha_g, alpha_b );
    gl_FragColor = vec4( color, 1.0 );
}
```
I haven't optimized it yet.

**Comment by oomek** [comment]
Apart from getting rid of artiffacts on overlapped glyphs It also makes quite a difference on small glyphs when fringes overlap. Corners now are also correctly rendered when left and right fringe merges, The spikes and overlaps should turn green or purple. I'm gonna post a screenshot in a sec.

**Comment by oomek** [comment]
![image](https://user-images.githubusercontent.com/2974860/75203887-4b03a700-5767-11ea-9073-197819a63ba4.png)

**Comment by oomek** [comment]
Have I mentioned yet how awesome your atlas generetor is ;) ? I'm seriously considering now the implementation of your sdf into Attract Mode frontend and maybe even into SFML framework which AM is using. All other sdf methods were completely unconvincing to me, but now I have a heavy weapon to challenge the fonts with static atlases :)

**Comment by astiopin** [comment]
> Could you tell me what was the reason of using a workaround mentioned here?

In desktop version I'm doing fancy things with text like gradients and texturing. The text color always comes from the shader as a SRC. I thought of using either blend_func_extended or shader_framebuffer_fetch for blending at the time. it never came to me that I can set constant color in blend function even I'm using only solid colors in the demo. It somehow felt unnatural at the moment. So I made it by passing background color to the shader. 

Your blending method seems better suited for the demo, I will put it into program if you don't mind.

>The shader is simplified

Not sure about the shader. You're making a dependent read there which is not good for performance. Also that purple stem in 'd' doesn't feel right since it should be purple only if there are two vertical edges in a pixel: R]  [B - solid R and B, empty B. This is not the case here - that stroke is spanning three pixels and should be either blue or red, not both.

>Have I mentioned yet how awesome your atlas generetor is 

Thanks! Glad I can help.

**Comment by oomek** [comment]
The demo will definitely benefit from this blending mode so go for it mate.

The stems can actually turn purple if the thickness of the black stem on light background is thinner that 1 pixel. The edges are not solid because of more relaxed horizontal gradient, that's how I see it.

Dependant reads can be squashed by moving some calculations to the vertex shader.

**Comment by oomek** [comment]
Look at this screenshot of chinese glyphs from wikipedia, the second glyph looks exactly the same.

![](https://upload.wikimedia.org/wikipedia/zh/2/2d/ClearType-ZHCN.jpg)

**Comment by astiopin** [comment]
>The stems can actually turn purple if the thickness of the black stem on light background is thinner that 1 pixel. The edges are not solid because of more relaxed horizontal gradient, that's how I see it.

Yeah, you are right. Forgot about the colors.

>Dependant reads can be squashed by moving some calculations to the vertex shader.

I think four reads should be enough without the second step. At least Qt does this by sampling 4 points in X-pattern IIRC. Should do the research. My method is not optimal of course - just the first thing I came up with.

**Comment by oomek** [comment]
I agree, the same samples can be used for detecting the slope direction and the subpixel channels. Just the offset needs to be calculated in the vs for the particular glyph size instead of using sdf_texel size

**Comment by DanielHerchenbach** [comment]
> Could you tell me what was the reason of using a workaround mentioned here?
> https://github.com/astiopin/webgl_fonts/blob/e83f9c6ba9bb3f43d15cd17660e0e928f7734956/src/fshader.js#L104
> 
> 
> I did some experiments and I've managed to do a proper blending for cleartype with 3 samples with offset for each channel instead of fake fringing.
> ```
>         gl.enable(gl.BLEND);
>         gl.blendFunc(gl.CONSTANT_COLOR, gl.ONE_MINUS_SRC_COLOR);
> 
>         gl.blendEquation( gl.FUNC_ADD );
>         gl.blendColor( font_color[0], font_color[1], font_color[2], 1.0);
> ```
@oomek Nice idea for the blending. Could you tell me what is the purpose of **blendEquation**? I tried with **blendFunc** only and it works as well.

**Comment by oomek** [comment]
The default `blendEquation` is `FUNC_ADD` so it can be removed if it's the only `blendEquation` used in blending your textures. I was doing various experiments around with different blending modes so I had to reset it back.

**Comment by DanielHerchenbach** [comment]
Thanks!
