### ISSUE TITLE
Advancing pen does not use kerning

### ISSUE THREAD

**Issue by DanielHerchenbach** [astiopin/webgl_fonts#8]
In function _charRect_ I think the following line
_var new_pos_x = pos[0] + font.aspect * scale * ( font_char.advance_x );_
should be changed to
_var new_pos_x = pos[0] + font.aspect * scale * ( font_char.advance_x + kern );_
because if the space between two chars is adapted (kerning), all subsequent chars in this line shall also be shifted.
To be absolutely correct I think there is another issue: one should not initialize the previous char to whitespace when a new line is started because I could imagine some fonts define kerning with whitespace (for example shift "V" a bit to left if preceded by a whitespace).

Remark: For my use case I prefer to apply the scale and rounding for hinting in vertical direction only and only locally for glyphs (i.e. I am not rounding the line height). Otherwise, the rounding errors cummulate and may change the global text layout which requires a relayout for every change of the font size.
On the other hand, when scaling only vertically, the resulting glyph distortion is too small to be noticeable.

**Comment by astiopin** [comment]
Sorry, I've missed your comments, notifications came only for recent messages. Fixed.
